name: Build Storybook

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "prod"
      - name: Install All
        run: npm i
      - name: Install Local
        run: cd packages/docs && npm i
      - name: Build All
        run: npm run build
      - name: Run Merge
        run: git add . && git commit -m "" && git push
