name: Build Storybook

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_U }}
          password: ${{ secrets.DOCKER }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install All
        run: npm i

      - name: Install Local
        run: cd packages/docs && npm i

      - name: Build All
        run: npm run build

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: raferdev/app:latest
