name: Deploy Storybook

on:
  push:
    branches:
      - deploy

name: Deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go path and Clear Docker
        run: cd packages/docs && sudo docker-compose down && sudo docker system prune --all --force
      - name: Build
        run: cd packages/docs && sudo docker-compose build
      - name: Run
        run: cd packages/docs && sudo docker-compose up -d