name: Deploy Storybook

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: cd packages/docs && sudo docker-compose build
      - name: Run
        run: cd packages/docs && sudo docker-compose up -d
